name: EAS Android Build
on:
    release:
        types: [published]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: 🏗 Setup repo
              uses: actions/checkout@v3

            - name: 🏗 Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: yarn

            - name: 🏗 Setup Expo
              uses: expo/expo-github-action@v7
              with:
                  expo-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: 📦 Install dependencies
              run: yarn install

            - name: 🚀 Build Android on EAS
              run: eas build --platform android --non-interactive
